version: '3'

services:
  mysql-server:
    image: mysql-server:0.0.1
    container_name: mysql-server
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: users-management
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: on-failure
  user-backend:
    image: user-backend:0.0.1
    container_name: user-backend
    build:
      context: ./user-management-backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql-server
    restart: on-failure
  user-frontend:
    image: user-frontend:0.0.1
    container_name: user-frontend
    build:
      context: ./user-management-frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - user-backend
    restart: on-failure
  